### ISSUE TITLE
Trying to get AutoDocumentFeed_for_WIA to work with .Net Framework 4.5

### ISSUE THREAD

**Issue by jdressing** [gideondsouza/AutoDocumentFeed_for_WIA#1]
I have a .Net app using the 4.5 framework and I cannot get your code to work with it?   If I try to recompile your code using the 4.5 framework I get all of these errors.   Any ideas how to get it to work?

I get the following error:

Error   6   Interop type 'WIA.CommonDialogClass' cannot be embedded. Use the applicable interface instead.
Error   7   The type 'WIA.DeviceManagerClass' has no constructors defined  
Error   9   Interop type 'WIA.FormatID' cannot be embedded. Use the applicable interface instead.

**Comment by jdressing** [comment]
I got it working... it just needed the Embed Interops set to False.

For some reason  when scanning using an ADF, it always scans an extra blank page... not sure why.  I am using an HP Scanner.  It works fine on flatbed and it always scans 1 additional blank page at the end when using the ADF.

Any ideas?

Thanks!!

**Comment by gideondsouza** [comment]
Thank you very much for adding the issue and it's solution. 

I'm recovering out of a hospitalization - brain tumor, so a lot of my projects have gone cold.
It'll be sometime before I update them. (Or I'll be in a state ti update them)

But Thanks again. 
Gideon
